print("###################################")
print("#                                 #")
print("#   Muhammad Ryan Rizky Rahmadi   #")
print("#         2210817310001           #")
print("#                                 #")
print("###################################")